{
 "title": "Puma Experimental",
 "time": { "from": "2024-11-21T11:24:47.548Z", "to": "2024-11-21T11:33:10.250Z" },
 "panels": [
  {
   "title": "Puma RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(puma_requests_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backlog size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum (puma_backlog)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AVG request wait_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(puma_requests_wait_time[1m])) / sum(rate(puma_requests_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}